#!/bin/bash

# Define variables
LOCALHOST_IP="127.0.0.2"
FACEBOOK_IP="8.8.8.8"

# Update /etc/hosts file
echo "$LOCALHOST_IP localhost" | sudo tee -a /etc/hosts
echo "$FACEBOOK_IP facebook.com" | sudo tee -a /etc/hosts

# Restart networking service
sudo service networking restart
