#!/bin/bash

# Update the system
sudo apt update && sudo apt upgrade -y

# Set up the hosts file
sudo sed -i '/^127.0.0.1/ s/$/ localhost 127.0.0.2/' /etc/hosts
sudo sed -i '$ a 8.8.8.8 facebook.com' /etc/hosts

# Restart the networking service
sudo systemctl restart networking.service
